### ISSUE TITLE
Update to latest faker

### ISSUE THREAD

**Issue by jens1o** [deerawan/vscode-faker#1]
Hi,

first of all: This extension is very useful!

Could you please update to the latest faker? 4.1 is out, but you're only using 3.1. I can make a pr if you would like to.

Regards,
Jens

**Comment by deerawan** [comment]
@jens1o Hi Jens, I updated to use latest faker 4.1
https://github.com/deerawan/vscode-faker/releases/tag/v1.1.0
https://marketplace.visualstudio.com/items?itemName=deerawan.vscode-faker

Thank you for using this extension 👍

**Comment by jens1o** [comment]
Thanks, very appreciated.
