### ISSUE TITLE
Add support for snippets

### ISSUE THREAD

**Issue by Antaris** [deerawan/vscode-faker#15]
Hi,

I'd love if I could use snippets to insert faker date, for instance, typing:

`let firstName = fake-firstname<tab>`, might be able to generate `let firstName = '<value>'`.

Not sure if VS Code supports this, but would save some keystrokes!

**Comment by deerawan** [comment]
Hey @Antaris 

Interesting idea! Let me see what I can do here. 👍

**Comment by deerawan** [comment]
seems it is not possible yet to do this in vscode. Adding a reference links: 
- https://github.com/microsoft/vscode/issues/10561
- https://code.visualstudio.com/docs/editor/userdefinedsnippets

I'll close the issue and reopened again once the feature is supported in vscode. Thanks for the idea!
