### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by 02ernesto** [deerawan/vscode-faker#17]
- Issue Type: `Performance`
- Extension Name: `vscode-faker`
- Extension Version: `1.3.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.36.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Ernesto\deerawan.vscode-faker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by deerawan** [comment]
Thank you @02ernesto for submitting this issue. Version 1.3.1 has been published that contains the fix.
