### ISSUE TITLE
Cannot generate in multi cursor point 

### ISSUE THREAD

**Issue by KytoSai** [deerawan/vscode-faker#2]
Plugin is good .But cannot generate random in multi cursor point 
Example: http://prntscr.com/gk272d

**Comment by deerawan** [comment]
@KytoSai thank you for filling this issue. I'll try to implement this feature as soon as possible.

**Comment by deerawan** [comment]
The feature has been released in `v1.2.0` 
https://github.com/deerawan/vscode-faker/releases/tag/v1.2.0

@KytoSai, would you mind updating the rating https://marketplace.visualstudio.com/items?itemName=deerawan.vscode-faker#review-details? Thank you 😃
