### ISSUE TITLE
Fake images from lorempixel.com don't work

### ISSUE THREAD

**Issue by Ares9323** [deerawan/vscode-faker#22]
I noticed the entire site is not loading, I tried to fork the project and fix it in a pull request but I couldn't find "lorempixel" in the entire extension folder.

As fake image provider i can suggest (for personal experience) placehold.it or placeimg.com

**Comment by deerawan** [comment]
Hi @Ares9323, thank you for creating the issue. You are right! I experienced same problem. 

The fix should be done in faker library itself. I found a related PR regarding this 

https://github.com/Marak/faker.js/pull/885
