### ISSUE TITLE
Command 'Faker: Name' resulted in an error (command 'faker.name' not found)

### ISSUE THREAD

**Issue by DiegoEDG** [deerawan/vscode-faker#34]
I'm just update vscode now and faker isn't works, how to fix that command error?

**Comment by deerawan** [comment]
@DiegoEDG could you give me more details, please? 

1) vscode version
2) faker version

**Comment by deerawan** [comment]
Hi @DiegoEDG, I just published `1.4.1`, could you update to that version and try again?

**Comment by DiegoEDG** [comment]
Faker works, I'm not update to 1.4.1 but it's works again

I'm using faker in 1.4.0 and VS code in 1.44.2

**Comment by deerawan** [comment]
great! I'll close this issue
