### ISSUE TITLE
[Feature Request] Add an email generator

### ISSUE THREAD

**Issue by ABODFTW** [deerawan/vscode-faker#36]

**Comment by deerawan** [comment]
Hi @ABODFTW, thank you for submitting the issue

`email` can be generated by using `faker.internet.email`

![Image 2022-02-16 at 19 24 09](https://user-images.githubusercontent.com/1243921/154224670-0558abf1-4e1c-493f-8304-12571a05e884.jpg)

Does it solve your issue?

**Comment by OneAbodFTW** [comment]
I don't even remember why I needed this, but I guess it solves it, Thanks a lot, closing this.
