### ISSUE TITLE
Faker: image-avatar

### ISSUE THREAD

**Issue by mattiasbonte** [deerawan/vscode-faker#40]
Hi Devs,

I can't seem to generate images that work anymore. If I chose avatar the access is denied. See example below. This is not a single occurrence but happened for the 15images I tried.

https://s3.amazonaws.com/uifaces/faces/twitter/horaciobella/128.jpg

```AllAccessDisabledAll access to this object has been disabled706424B4CFE71019D+h1xLqjzT5+snt13WRuiT+oyqhmxYFsSswjIXA4yH/9RTiuAxCk0laqn4lcEYYQ5NVsr4TxDEg=```

Cheers!

**Comment by deerawan** [comment]
Hi @mattiasbonte 

I checked the functionality in `@faker-js` package for `avatar`, seems it has been fixed. I'll publish the next version of the plugin soon that contains the fix.

**Comment by deerawan** [comment]
I just published v2.0.0 in the marketplace. I tried `faker.image.avatar` and it worked great. 

Here's the generated URL https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/839.jpg

I'll close this ticket

Thank you
