### ISSUE TITLE
After the recent faker.js issues, is this still safe to use?

### ISSUE THREAD

**Issue by Svish** [deerawan/vscode-faker#49]
As far as I understand this extension is based upon the faker.js library which has recently had some... interesting updates...

Is this extension still safe to use?

**Comment by TryTryAgain** [comment]
The package version in package-lock isn't using the 6.6.6 version. ;)

**Comment by deerawan** [comment]
Hey, thanks for submitting the issue. I'm planning to update the package to https://github.com/faker-js/faker
