### ISSUE TITLE
Some Random selections not working

### ISSUE THREAD

**Issue by timharris777** [deerawan/vscode-faker#9]
Number and Boolean under Random are not doing anything. All other selections seem to work fine. I am on the latest stable version of VS Studio and installed the plugin from the extension marketplace.

**Comment by ReggaePanda** [comment]
i have the same problem 

```
code -v
1.18.1
```

**Comment by deerawan** [comment]
@timharris777 and @ReggaePanda thank you for reporting the bug. 👍 

It is fixed in latest vscode faker v1.2.1
https://marketplace.visualstudio.com/items?itemName=deerawan.vscode-faker

Let me know if you still found the issue

**Comment by ReggaePanda** [comment]
@deerawan random number and boolean works now 🥇

**Comment by deerawan** [comment]
awesome, I'll close the issue 😄
